import {
  FIELD_TYPES,
  FIELD_WIDTH,
} from "../../../../application-definition/constants.js";

export const knowledgeOfCareFields = [
  {
    id: "understanding-personal-care",
    type: FIELD_TYPES.NUMBER,
    name: "scores.understandingPersonalCare",
    label: "Understanding of Personal Care",
    placeholder: "Score from 0 to 5",
    required: true,
    min: 0,
    max: 5,
    step: 1,
    helpText: "Explains the importance of personal hygiene.",
    order: 1,
    width: FIELD_WIDTH.HALF,
  },

  {
    id: "handling-mobility-issues",
    type: FIELD_TYPES.NUMBER,
    name: "scores.handlingMobilityIssues",
    label: "Handling Mobility Issues",
    placeholder: "Score from 0 to 5",
    required: true,
    min: 0,
    max: 5,
    step: 1,
    helpText: "Demonstrates knowledge of assisting clients with mobility.",
    order: 2,
    width: FIELD_WIDTH.HALF,
  },

  {
    id: "health-safety-awareness",
    type: FIELD_TYPES.NUMBER,
    name: "scores.healthSafetyAwareness",
    label: "Health & Safety Awareness",
    placeholder: "Score from 0 to 5",
    required: true,
    min: 0,
    max: 5,
    step: 1,
    helpText: "Recognizes risks such as falls and infections.",
    order: 3,
    width: FIELD_WIDTH.HALF,
  },

  {
    id: "knowledge-of-safeguarding",
    type: FIELD_TYPES.NUMBER,
    name: "scores.knowledgeOfSafeguarding",
    label: "Knowledge of Safeguarding",
    placeholder: "Score from 0 to 5",
    required: true,
    min: 0,
    max: 5,
    step: 1,
    helpText: "Understands confidentiality and abuse reporting.",
    order: 4,
    width: FIELD_WIDTH.HALF,
  },

  {
    id: "nutrition-meal-preparation",
    type: FIELD_TYPES.NUMBER,
    name: "scores.nutritionMealPreparation",
    label: "Nutrition & Meal Preparation",
    placeholder: "Score from 0 to 5",
    required: true,
    min: 0,
    max: 5,
    step: 1,
    helpText: "Demonstrates a basic understanding of balanced meals.",
    order: 5,
    width: FIELD_WIDTH.HALF,
  },
];
