export const AUDIT_ACTIONS = {
  APPLICATION_SECTION_APPROVED: "APPLICATION_SECTION_APPROVED",

  APPLICATION_SECTION_REJECTED: "APPLICATION_SECTION_REJECTED",

  APPLICATION_SECTION_IN_PROGRESS: "APPLICATION_SECTION_IN_PROGRESS",

  APPLICATION_PHASE_APPROVED: "APPLICATION_PHASE_APPROVED",

  APPLICATION_PHASE_UPDATED: "APPLICATION_PHASE_UPDATED",

  APPLICATION_STATUS_UPDATED: "APPLICATION_STATUS_UPDATED",

  APPLICATION_STAGE_UPDATED: "APPLICATION_STAGE_UPDATED",

  STAFF_UPDATED: "STAFF_UPDATED",

  STAFF_COMPLIANCE_UPDATED: "STAFF_COMPLIANCE_UPDATED",

  //AUthethication
  USER_REGISTERED: "USER_REGISTERED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  PASSWORD_CREATED: "PASSWORD_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",

  USER_LOGGED_OUT_ALL_DEVICES: "USER_LOGGED_OUT_ALL_DEVICES",

  //APPlication
  APPLICATION_SECTION_CREATED: "APPLICATION_SECTION_CREATED",

  APPLICATION_SECTION_UPDATED: "APPLICATION_SECTION_UPDATED",

  APPLICATION_SECTION_SUBMITTED: "APPLICATION_SECTION_SUBMITTED",
  APPLICATION_SECTION_DRAFT_SAVED: "APPLICATION_SECTION_DRAFT_SAVED",

  APPLICATION_PHASE_SUBMITTED: "APPLICATION_PHASE_SUBMITTED",
  SECTION_REVIEW_COMMENT_CREATED: "SECTION_REVIEW_COMMENT_CREATED",
  APPLICATION_SECTION_STATUS_UPDATED: "APPLICATION_SECTION_STATUS_UPDATED",
  SECTION_REVIEW_COMMENT_UPDATED: "APPLICATION_SECTION_STATUS_UPDATED",
  SECTION_REVIEW_COMMENT_DELETED: "SECTION_REVIEW_COMMENT_DELETED",

  //REference
  REFERENCE_CREATED: "REFERENCE_CREATED",
  REFERENCE_UPDATED: "REFERENCE_UPDATED",
  REFERENCE_SUBMITTED: "REFERENCE_SUBMITTED",
  REFERENCE_APPROVED: "REFERENCE_APPROVED",
  REFERENCE_DELETED: "REFERENCE_DELETED",
  REFERENCE_REJECTED: "REFERENCE_REJECTED",
  REFERENCE_MAIL_SENT: "REFERENCE_MAIL_SENT",
  REFERENCE_MAIL_STATUS_UPDATED: "REFERENCE_MAIL_STATUS_UPDATED",
  REFERENCE_RESPONSE_CREATED: "REFERENCE_RESPONSE_CREATED",
  REFERENCE_RESPONSE_UPDATED: "REFERENCE_RESPONSE_UPDATED",

  //Training Certificate
  TRAINING_CERTIFICATE_REQUIREMENT_CREATED:
    "TRAINING_CERTIFICATE_REQUIREMENT_CREATED",
  TRAINING_CERTIFICATE_REQUIREMENT_UPDATED:
    "TRAINING_CERTIFICATE_REQUIREMENT_UPDATED",
  TRAINING_CERTIFICATE_REQUIREMENT_ACTIVATED:
    "TRAINING_CERTIFICATE_REQUIREMENT_ACTIVATED",
  TRAINING_CERTIFICATE_REQUIREMENT_DEACTIVATED:
    "TRAINING_CERTIFICATE_REQUIREMENT_DEACTIVATED",

  // Training Certificate

  TRAINING_CERTIFICATE_CREATED: "TRAINING_CERTIFICATE_CREATED",

  TRAINING_CERTIFICATE_UPDATED: "TRAINING_CERTIFICATE_UPDATED",

  TRAINING_CERTIFICATE_DELETED: "TRAINING_CERTIFICATE_DELETED",

  // Interview

  INTERVIEW_CREATED: "INTERVIEW_CREATED",

  INTERVIEW_UPDATED: "INTERVIEW_UPDATED",

  INTERVIEW_NOTE_CREATED: "INTERVIEW_NOTE_CREATED",
  INTERVIEW_NOTE_UPDATED: "INTERVIEW_NOTE_UPDATED",
  INTERVIEW_NOTE_DELETED: "INTERVIEW_NOTE_DELETED",
};
