export const AUDIT_ACTIONS = {
  APPLICATION_SECTION_CREATED: "APPLICATION_SECTION_CREATED",

  APPLICATION_SECTION_UPDATED: "APPLICATION_SECTION_UPDATED",

  APPLICATION_SECTION_SUBMITTED: "APPLICATION_SECTION_SUBMITTED",

  APPLICATION_SECTION_APPROVED: "APPLICATION_SECTION_APPROVED",

  APPLICATION_SECTION_REJECTED: "APPLICATION_SECTION_REJECTED",

  APPLICATION_SECTION_IN_PROGRESS: "APPLICATION_SECTION_IN_PROGRESS",

  APPLICATION_PHASE_APPROVED: "APPLICATION_PHASE_APPROVED",

  APPLICATION_PHASE_UPDATED: "APPLICATION_PHASE_UPDATED",

  APPLICATION_STATUS_UPDATED: "APPLICATION_STATUS_UPDATED",

  APPLICATION_STAGE_UPDATED: "APPLICATION_STAGE_UPDATED",

  STAFF_UPDATED: "STAFF_UPDATED",

  STAFF_COMPLIANCE_UPDATED: "STAFF_COMPLIANCE_UPDATED",
  USER_REGISTERED: "USER_REGISTERED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  PASSWORD_CREATED: "PASSWORD_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",

  USER_LOGGED_OUT_ALL_DEVICES: "USER_LOGGED_OUT_ALL_DEVICES",
};
